In [2]:
import requests
from bs4 import BeautifulSoup
import concurrent.futures
import pandas as pd

def scrape_holidays(year):
    url = f"https://www.timeanddate.com/holidays/pakistan/{year}?hol=1"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    table = soup.find('table', {'class': 'table table--left table--inner-borders-rows table--full-width table--sticky table--holidaycountry'})
    for row in table('tr', {'class': 'hiderow'}):
        row.decompose()
    df = pd.read_html(str(table), header=1)[0]
    df = df.drop([0, 1])
    df.dropna(inplace=True)
    df['Year'] = year
    return df


def print_progress(year):
    print(f"Finished scraping holidays for {year}")


all_data = pd.DataFrame()
years = range(2014, 2021)

with concurrent.futures.ThreadPoolExecutor() as executor:
    results = [executor.submit(scrape_holidays, year) for year in years]
    for f in concurrent.futures.as_completed(results):
        df = f.result()
        all_data = pd.concat([all_data, df], ignore_index=True)

df=all_data
print(df)
df['Date'] = df['Date'].replace(r'^\s*$', '01 Jan', regex=True)
df['Year'] = df['Year'].astype(str)  # convert 'Year' column to string type

df['Date'] = df['Date'] + ' ' + df['Year']
df['Date'] = pd.to_datetime(df['Date'], format='%d %b %Y')

import pandas as pd
DailyDataset = pd.read_csv('DailyDataset.csv')
DailyDataset['Date'] = pd.to_datetime(DailyDataset['Date'])

df['Date'] = pd.to_datetime(df['Date'])
matching_dates = df['Date']

# create a new column 'Event' and initialize it to 0
DailyDataset['Event'] = 0

# update the 'Event' column to 1 for matching dates
DailyDataset.loc[DailyDataset['Date'].isin(matching_dates), 'Event'] = 1

# print the updated DataFrame
DailyDataset.to_csv('DailyDataset')

       Date Unnamed: 1                 Name            Type  Year
0     5 Feb  Wednesday          Kashmir Day  Public Holiday  2014
1    23 Mar     Sunday         Pakistan Day  Public Holiday  2014
2     1 May   Thursday           Labour Day  Public Holiday  2014
3    29 Jul    Tuesday          Eid-ul-Fitr  Public Holiday  2014
4    30 Jul  Wednesday  Eid-ul-Fitr Holiday  Public Holiday  2014
..      ...        ...                  ...             ...   ...
116  11 Oct    Tuesday               Ashura  Public Holiday  2016
117  12 Oct  Wednesday       Ashura Holiday  Public Holiday  2016
118  12 Dec     Monday    Eid Milad un-Nabi  Public Holiday  2016
119  25 Dec     Sunday        Christmas Day  Public Holiday  2016
120  25 Dec     Sunday     Quaid-e-Azam Day  Public Holiday  2016

[121 rows x 5 columns]

KeyError: 'Date'

In [55]:
pd.set_option('display.max_rows', None)

DailyDataset.head(300)

,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Temperature,Dew Point,Humidity,Wind Speed,Wind,Pressure,IntCondition,Year,Month,Day,Date,Event
0,0,4,3,32,7,0,0,2,61.937500,15.125000,17.562500,15.687500,35.375000,30.070000,1.250000,2014,1,2,2014-01-02,0
1,8,4,4,50,16,0,20,4,60.043478,21.565217,25.521739,8.173913,144.086957,30.008696,1.000000,2014,1,3,2014-01-03,0
2,2,1,6,61,9,0,9,1,61.727273,37.272727,45.545455,5.500000,106.500000,28.555909,1.000000,2014,1,4,2014-01-04,0
3,4,3,7,41,8,0,3,0,61.347826,25.956522,33.260870,4.913043,58.869565,29.910435,1.000000,2014,1,5,2014-01-05,0
4,5,1,4,21,16,2,6,2,59.227273,25.818182,28.772727,8.227273,46.227273,24.507273,1.409091,2014,1,6,2014-01-06,0
5,0,0,0,0,0,0,0,0,61.136364,19.590909,23.272727,8.318182,40.227273,29.934091,1.000000,2014,1,7,2014-01-07,0
6,5,3,9,26,17,1,10,0,59.714286,24.809524,29.285714,6.666667,60.333333,29.915714,2.238095,2014,1,8,2014-01-08,0
7,7,1,6,24,13,0,3,2,58.181818,23.000000,36.318182,6.909091,25.681818,29.990909,1.000000,2014,1,9,2014-01-09,0
8,5,1,2,52,14,2,0,2,57.210526,22.105263,32.368421,7.368421,53.421053,29.978421,1.631579,2014,1,10,2014-01-10,0
9,4,2,10,43,10,0,1,0,59.904762,23.142857,28.952381,7.571429,37.714286,28.639524,2.428571,2014,1,11,2014-01-11,0
10,2,0,3,12,8,0,1,1,60.181818,25.727273,29.909091,6.636364,48.363636,30.076818,3.090909,2014,1,12,2014-01-12,0
11,6,7,4,51,8,0,7,1,62.636364,33.545455,38.045455,6.181818,84.045455,30.012727,3.818182,2014,1,13,2014-01-13,0
12,6,2,12,34,6,1,0,2,63.086957,30.260870,43.478261,6.652174,89.173913,26.066957,1.000000,2014,1,14,2014-01-14,0
13,4,2,5,27,12,2,3,3,64.181818,36.363636,41.909091,7.181818,103.545455,30.015455,1.000000,2014,1,15,2014-01-15,0
14,6,2,4,28,19,1,5,0,63.818182,34.681818,39.818182,7.000000,92.318182,27.275000,1.000000,2014,1,16,2014-01-16,0
15,2,4,8,20,15,0,6,3,65.173913,42.913043,48.130435,7.304348,99.000000,29.933913,1.565217,2014,1,17,2014-01-17,0
16,1,5,5,43,15,4,7,2,64.391304,27.260870,33.913043,7.782609,103.043478,29.994348,1.000000,2014,1,18,2014-01-18,0
17,4,4,4,14,4,0,1,1,63.434783,36.173913,40.086957,15.478261,29.478261,24.863913,1.478261,2014,1,19,2014-01-19,0
18,6,3,3,10,17,2,12,3,64.900000,43.450000,48.300000,20.050000,46.250000,30.020500,3.250000,2014,1,20,2014-01-20,0
19,2,3,4,33,10,2,0,0,63.700000,42.300000,49.000000,10.050000,37.400000,29.999500,2.300000,2014,1,21,2014-01-21,0
20,7,3,5,16,10,0,5,2,65.619048,43.714286,48.238095,8.000000,124.523809,30.007143,1.380952,2014,1,22,2014-01-22,0
21,4,4,5,26,2,3,1,3,64.833333,46.791667,56.583333,7.583333,71.500000,30.032500,1.250000,2014,1,23,2014-01-23,0
22,4,7,7,20,10,1,0,0,64.869565,40.347826,43.260870,7.304348,36.434783,27.421304,1.043478,2014,1,24,2014-01-24,0
23,6,9,5,37,18,0,5,1,65.636364,38.636364,43.772727,7.590909,73.954545,29.999091,1.727273,2014,1,25,2014-01-25,0
24,4,2,0,24,4,0,0,0,67.260870,39.217391,42.173913,7.869565,55.000000,28.697391,1.000000,2014,1,26,2014-01-26,0
25,4,4,1,24,17,2,1,3,68.521739,36.478261,36.217391,10.260870,40.347826,30.006087,2.391304,2014,1,27,2014-01-27,0
26,6,3,3,13,22,5,1,5,70.173913,36.434783,33.347826,7.260870,141.130435,29.969565,2.043478,2014,1,28,2014-01-28,0
27,4,1,2,12,7,0,1,2,66.500000,47.681818,54.090909,7.727273,134.181818,28.558636,1.000000,2014,1,29,2014-01-29,0
28,2,1,2,26,7,1,3,2,67.565217,43.782609,48.000000,7.565217,93.173913,29.944783,3.000000,2014,1,30,2014-01-30,0
29,1,2,7,27,9,0,1,0,71.380952,47.047619,47.809524,7.142857,133.190476,28.510952,1.761905,2014,1,31,2014-01-31,0
30,4,5,5,43,13,1,14,0,71.956522,45.739130,41.913043,6.478261,76.521739,29.904783,3.869565,2014,2,1,2014-02-01,0
31,7,3,0,13,6,2,8,0,70.869565,44.347826,40.652174,7.086957,157.739130,28.584348,3.173913,2014,2,2,2014-02-02,0
32,4,1,6,28,13,1,1,0,69.600000,53.850000,58.550000,10.900000,184.750000,28.379000,1.900000,2014,2,3,2014-02-03,0
33,1,3,7,31,8,1,17,2,71.565217,58.956522,67.347826,8.260870,122.478261,28.530870,1.000000,2014,2,4,2014-02-04,0
34,3,4,6,32,15,1,1,1,71.173913,61.260870,72.173913,8.130435,209.521739,27.193043,1.391304,2014,2,5,2014-02-05,1
35,3,6,4,41,17,2,5,2,72.652174,62.869565,72.608696,10.826087,257.521739,29.746087,4.826087,2014,2,6,2014-02-06,0
36,2,8,11,21,19,1,0,0,68.565217,33.043478,32.304348,14.043478,261.391304,29.801304,1.434783,2014,2,7,2014-02-07,0
37,2,2,13,30,12,1,1,1,63.545455,29.409091,35.181818,7.000000,134.227273,29.829545,1.000000,2014,2,8,2014-02-08,0
38,4,3,2,31,10,0,6,0,63.043478,31.695652,37.913043,7.608696,97.000000,29.834783,1.000000,2014,2,9,2014-02-09,0
39,5,10,8,32,16,3,3,1,65.590909,32.545455,35.454545,10.500000,200.772727,28.429091,2.272727,2014,2,10,2014-02-10,0
40,10,6,13,45,20,2,6,2,65.681818,25.545455,28.181818,7.000000,133.136364,29.816818,1.000000,2014,2,11,2014-02-11,0
41,9,1,9,74,9,0,5,0,66.695652,24.521739,22.869565,12.956522,52.086957,29.802174,1.217391,2014,2,12,2014-02-12,0
42,4,3,10,48,13,3,0,1,67.750000,25.333333,27.625000,12.791667,102.541667,28.539167,3.750000,2014,2,13,2014-02-13,0
43,4,4,3,42,13,4,0,6,67.409091,27.318182,31.545455,7.000000,158.818182,28.452273,3.318182,2014,2,14,2014-02-14,0
44,1,2,2,37,9,0,1,5,68.190476,30.809524,31.238095,11.047619,267.142857,29.790000,1.000000,2014,2,15,2014-02-15,0
45,0,2,1,34,5,2,3,1,66.086957,19.739130,24.565217,11.086957,35.434783,29.890435,1.043478,2014,2,16,2014-02-16,0
46,7,4,12,27,13,1,7,0,68.304348,21.521739,18.391304,10.652174,65.826087,29.998261,1.173913,2014,2,17,2014-02-17,0
47,7,7,6,45,14,0,13,5,67.217391,26.347826,26.869565,6.565217,136.217391,29.959130,1.000000,2014,2,18,2014-02-18,0
48,3,5,5,66,17,1,6,1,67.590909,50.454545,54.909091,9.363636,212.909091,29.865000,1.409091,2014,2,19,2014-02-19,0
49,6,6,3,21,14,1,8,1,66.952381,51.619048,59.380952,8.904762,148.095238,28.409048,1.000000,2014,2,20,2014-02-20,0
50,6,4,8,20,16,0,0,0,70.476190,50.142857,54.619048,6.714286,142.761905,29.843333,1.000000,2014,2,21,2014-02-21,0
51,7,3,6,26,12,0,1,0,70.826087,35.347826,37.565217,11.434783,55.956522,29.931739,1.000000,2014,2,22,2014-02-22,0
52,1,3,2,21,10,0,0,0,68.450000,34.500000,31.450000,10.650000,37.250000,29.993500,1.250000,2014,2,23,2014-02-23,0
53,7,4,5,26,4,0,0,3,71.250000,33.458333,27.125000,18.291667,32.166667,29.970000,3.333333,2014,2,24,2014-02-24,0
54,5,1,11,35,13,0,0,2,71.636364,34.454545,29.818182,8.454545,124.954545,28.572273,1.863636,2014,2,25,2014-02-25,0
55,4,4,1,22,4,0,12,1,69.190476,44.333333,44.571429,6.571429,133.047619,29.877619,1.000000,2014,2,26,2014-02-26,0
56,3,6,4,33,8,1,2,1,73.086957,35.304348,36.739130,11.043478,189.043478,29.830000,1.086957,2014,2,27,2014-02-27,0
57,7,8,6,37,12,1,2,0,68.666667,43.250000,41.750000,6.916667,133.291667,28.612083,1.625000,2014,2,28,2014-02-28,0
58,6,3,11,50,8,0,0,2,68.166667,43.166667,46.958333,7.291667,135.250000,29.891250,1.000000,2014,3,1,2014-03-01,0
59,3,1,2,6,2,0,0,1,70.260870,58.260870,66.782609,9.043478,175.434783,29.895652,3.130435,2014,3,2,2014-03-02,0
60,4,3,1,21,1,2,0,2,70.478261,58.826087,69.130435,7.521739,149.826087,29.889565,4.304348,2014,3,3,2014-03-03,0
61,5,6,7,47,9,0,5,4,71.826087,58.130435,64.913043,10.565217,74.652174,29.923913,3.608696,2014,3,4,2014-03-04,0
62,2,1,3,24,4,0,1,0,71.227273,54.454545,58.136364,8.181818,176.181818,29.935909,1.318182,2014,3,5,2014-03-05,0
63,3,2,5,44,17,1,5,1,74.260870,54.391304,53.826087,7.652174,125.521739,29.910435,1.000000,2014,3,6,2014-03-06,0
64,4,4,9,25,3,1,0,2,76.739130,50.000000,44.217391,7.086957,123.478261,28.610870,1.000000,2014,3,7,2014-03-07,0
65,4,3,1,27,11,0,0,0,78.904762,45.476190,35.523810,7.904762,146.047619,29.922857,1.000000,2014,3,8,2014-03-08,0
66,1,0,4,11,3,0,5,0,76.565217,47.913043,38.043478,6.565217,141.173913,29.880435,1.000000,2014,3,9,2014-03-09,0
67,6,4,3,46,10,0,0,2,76.227273,58.000000,55.545455,9.318182,216.000000,29.815000,1.000000,2014,3,10,2014-03-10,0
68,6,5,7,31,12,1,1,5,74.521739,31.739130,26.478261,9.000000,181.173913,29.844783,1.652174,2014,3,11,2014-03-11,0
69,6,2,6,20,22,3,2,2,75.333333,21.904762,17.619048,15.238095,58.095238,29.934286,1.285714,2014,3,12,2014-03-12,0
70,2,3,5,15,10,0,26,2,76.565217,27.304348,21.217391,13.695652,39.391304,29.952609,1.130435,2014,3,13,2014-03-13,0
71,4,1,1,16,11,0,1,2,78.681818,36.727273,24.181818,7.454545,124.000000,29.888636,1.954545,2014,3,14,2014-03-14,0
72,4,2,11,23,18,1,6,2,79.434783,36.695652,23.826087,7.260870,179.260870,29.880435,2.956522,2014,3,15,2014-03-15,0
73,2,2,1,13,6,0,0,4,80.086957,49.260870,35.043478,10.521739,215.434783,29.908261,3.565217,2014,3,16,2014-03-16,0
74,8,3,6,36,6,1,0,1,79.263158,56.473684,47.052632,13.263158,257.263158,29.878421,2.210526,2014,3,17,2014-03-17,0
75,8,4,5,20,9,0,0,4,77.608696,47.043478,40.478261,8.086957,192.956522,29.897826,1.695652,2014,3,18,2014-03-18,0
76,4,3,4,21,2,0,0,2,78.000000,37.166667,25.416667,8.041667,150.208333,29.885417,1.000000,2014,3,19,2014-03-19,0
77,3,5,1,38,5,0,7,4,75.000000,52.478261,49.739130,8.739130,213.608696,28.499565,2.043478,2014,3,20,2014-03-20,0
78,6,3,5,40,4,0,2,1,76.208333,63.708333,66.125000,13.333333,261.708333,28.471667,1.791667,2014,3,21,2014-03-21,0
79,3,2,0,26,10,2,18,8,79.045455,65.318182,64.954545,9.500000,231.363636,29.679091,3.045455,2014,3,22,2014-03-22,0
80,6,2,4,19,0,1,0,3,74.304348,59.478261,59.391304,7.652174,184.173913,29.723913,2.304348,2014,3,23,2014-03-23,1
81,5,1,4,23,7,0,6,3,78.291667,59.666667,55.125000,10.000000,141.000000,29.792500,3.625000,2014,3,24,2014-03-24,0
82,3,1,9,36,6,0,1,1,74.956522,52.826087,48.347826,9.086957,217.521739,29.827826,2.478261,2014,3,25,2014-03-25,0
83,2,4,9,6,7,3,3,0,80.041667,46.333333,32.333333,8.875000,175.583333,29.807500,4.416667,2014,3,26,2014-03-26,0
84,4,0,2,20,6,1,1,5,82.217391,46.782609,29.347826,7.173913,209.695652,28.513913,4.695652,2014,3,27,2014-03-27,0
85,2,2,8,11,3,0,9,5,77.791667,57.083333,49.875000,8.666667,222.500000,29.815000,4.375000,2014,3,28,2014-03-28,0
86,4,6,4,24,8,2,9,3,78.826087,58.217391,52.000000,9.434783,193.956522,29.833478,1.782609,2014,3,29,2014-03-29,0
87,3,2,0,12,4,0,0,7,80.041667,60.000000,53.333333,8.291667,223.333333,27.327083,2.416667,2014,3,30,2014-03-30,0
88,5,2,4,15,6,1,4,6,80.416667,58.250000,50.208333,10.666667,273.083333,29.757500,1.250000,2014,3,31,2014-03-31,0
89,4,1,6,27,5,3,3,1,80.043478,63.826087,60.695652,14.043478,260.391304,28.435652,2.086957,2014,4,1,2014-04-01,0
90,2,4,8,23,1,0,7,3,79.500000,68.250000,70.416667,10.083333,245.041667,28.462917,3.083333,2014,4,2,2014-04-02,0
91,1,1,3,19,4,0,0,4,80.190476,67.428571,66.571429,7.666667,232.714286,29.755714,2.142857,2014,4,3,2014-04-03,0
92,3,3,3,24,9,3,8,2,81.125000,65.208333,61.375000,10.333333,272.208333,29.780000,2.333333,2014,4,4,2014-04-04,0
93,1,7,7,20,5,0,5,3,79.043478,67.869565,69.608696,10.652174,264.347826,29.760435,3.086957,2014,4,5,2014-04-05,0
94,2,1,1,19,1,0,0,1,83.900000,63.900000,54.500000,13.800000,272.600000,29.750000,3.550000,2014,4,6,2014-04-06,0
95,6,6,6,32,4,0,0,1,82.875000,41.291667,31.791667,9.375000,178.250000,29.831250,3.333333,2014,4,7,2014-04-07,0
96,4,2,1,19,6,1,0,4,80.166667,49.375000,36.625000,9.166667,192.333333,29.817500,3.375000,2014,4,8,2014-04-08,0
97,6,0,1,18,2,1,2,3,74.916667,57.333333,55.291667,8.041667,209.375000,29.797500,2.041667,2014,4,9,2014-04-09,0
98,3,2,1,18,10,0,4,4,80.130435,63.913043,60.782609,8.565217,230.260870,29.804783,2.347826,2014,4,10,2014-04-10,0
99,6,4,3,25,2,2,0,2,82.619048,60.761905,49.952381,12.047619,274.571429,28.357619,1.000000,2014,4,11,2014-04-11,0
100,6,3,6,23,17,0,11,4,80.130435,66.565217,64.130435,11.565217,255.521739,29.716087,1.260870,2014,4,12,2014-04-12,0
101,3,2,2,6,3,0,5,2,80.791667,68.166667,66.750000,11.750000,263.750000,29.692500,2.125000,2014,4,13,2014-04-13,0
102,1,4,5,28,10,0,5,5,82.125000,70.250000,68.083333,8.500000,233.666667,28.496667,3.500000,2014,4,14,2014-04-14,0
103,4,3,6,18,12,0,10,1,83.916667,70.625000,65.625000,8.166667,241.166667,29.776250,3.750000,2014,4,15,2014-04-15,0
104,2,0,4,25,1,0,6,4,83.545455,70.272727,65.136364,10.909091,272.318182,29.722727,2.363636,2014,4,16,2014-04-16,0
105,5,0,7,16,19,0,0,0,82.166667,71.000000,69.083333,10.083333,254.333333,28.402917,2.750000,2014,4,17,2014-04-17,0
106,7,7,6,17,10,1,0,3,83.772727,71.545455,67.636364,9.181818,201.681818,29.714545,5.363636,2014,4,18,2014-04-18,0
107,7,3,4,22,7,0,3,5,84.500000,69.958333,62.791667,8.750000,214.041667,29.756250,1.958333,2014,4,19,2014-04-19,0
108,0,0,0,0,0,0,0,0,85.782609,67.782609,59.521739,12.217391,201.782609,29.740870,3.391304,2014,4,20,2014-04-20,0
109,1,2,2,13,8,0,0,1,86.083333,51.916667,31.625000,8.083333,127.750000,29.745000,3.708333,2014,4,21,2014-04-21,0
110,5,7,3,32,8,1,0,1,85.625000,55.833333,36.666667,8.333333,192.500000,28.601250,1.375000,2014,4,22,2014-04-22,0
111,6,2,3,24,8,1,2,1,88.045455,55.045455,35.545455,10.090909,262.181818,29.812727,1.954545,2014,4,23,2014-04-23,0
112,2,2,1,26,6,0,6,2,84.125000,68.958333,61.958333,13.208333,274.083333,29.725000,1.791667,2014,4,24,2014-04-24,0
113,3,1,5,25,10,1,1,3,84.791667,72.250000,67.250000,11.625000,268.458333,29.703750,3.125000,2014,4,25,2014-04-25,0
114,1,2,5,35,11,1,0,4,88.600000,64.700000,49.500000,8.450000,256.700000,26.742000,2.850000,2014,4,26,2014-04-26,0
115,4,2,2,26,2,0,1,1,89.166667,66.875000,50.750000,9.166667,259.041667,29.721250,1.375000,2014,4,27,2014-04-27,0
116,1,2,3,29,8,2,0,2,91.500000,62.166667,44.333333,11.458333,280.541667,29.702500,1.000000,2014,4,28,2014-04-28,0
117,3,2,4,24,6,1,5,0,88.043478,65.217391,49.608696,11.217391,264.347826,29.658696,1.347826,2014,4,29,2014-04-29,0
118,4,2,7,42,11,0,7,4,85.956522,72.043478,64.217391,11.217391,267.173913,29.648261,2.347826,2014,4,30,2014-04-30,0
119,0,0,0,0,0,0,0,0,85.826087,72.608696,62.130435,13.260870,271.173913,29.639130,1.739130,2014,5,1,2014-05-01,1
120,7,7,6,39,16,1,12,2,85.434783,73.521739,68.869565,13.869565,268.304348,29.594783,3.043478,2014,5,2,2014-05-02,0
121,4,5,2,15,5,2,0,2,85.869565,74.304348,69.347826,11.652174,268.260870,29.580435,4.217391,2014,5,3,2014-05-03,0
122,1,4,1,20,3,0,0,3,86.291667,71.541667,63.708333,10.125000,162.416667,25.887500,3.500000,2014,5,4,2014-05-04,0
123,3,6,5,20,7,0,3,4,87.250000,64.166667,46.541667,10.541667,203.625000,29.638750,3.291667,2014,5,5,2014-05-05,0
124,7,4,4,22,10,2,6,5,89.916667,67.666667,49.875000,10.875000,268.333333,28.454167,1.375000,2014,5,6,2014-05-06,0
125,3,5,3,16,8,1,3,11,89.434783,64.565217,46.086957,10.695652,274.130435,29.666522,1.000000,2014,5,7,2014-05-07,0
126,1,2,1,19,6,1,0,5,90.266667,65.666667,45.866667,14.800000,265.666667,29.638000,1.133333,2014,5,8,2014-05-08,0
127,2,4,4,14,12,2,1,2,88.809524,67.666667,53.428571,13.619048,270.285714,29.561429,1.285714,2014,5,9,2014-05-09,0
128,5,6,9,39,15,3,1,5,87.761905,72.904762,62.380952,11.952381,244.619048,29.514286,1.190476,2014,5,10,2014-05-10,0
129,2,3,1,17,7,0,1,4,86.375000,73.708333,66.666667,14.041667,249.666667,29.620000,4.500000,2014,5,11,2014-05-11,0
130,4,3,9,12,8,0,5,2,85.791667,72.291667,64.625000,19.083333,246.041667,28.417917,7.500000,2014,5,12,2014-05-12,0
131,3,0,6,32,7,0,25,7,85.875000,73.000000,66.041667,19.375000,248.916667,29.642500,5.333333,2014,5,13,2014-05-13,0
132,1,2,5,22,3,0,0,3,85.000000,71.826087,65.521739,15.130435,217.478261,28.376957,4.521739,2014,5,14,2014-05-14,0
133,2,1,3,19,7,0,1,2,84.333333,70.791667,64.333333,12.083333,206.541667,29.662500,4.208333,2014,5,15,2014-05-15,0
134,5,7,3,22,10,1,11,1,86.291667,73.041667,65.000000,11.958333,243.125000,29.626250,4.375000,2014,5,16,2014-05-16,0
135,2,7,3,35,14,1,0,2,86.826087,68.130435,56.173913,10.173913,237.130435,29.688696,3.478261,2014,5,17,2014-05-17,0
136,3,2,5,9,6,0,0,1,85.458333,68.250000,57.500000,10.750000,244.083333,29.730000,1.666667,2014,5,18,2014-05-18,0
137,8,3,6,12,5,0,3,9,87.291667,67.083333,52.708333,9.875000,263.666667,29.736250,1.000000,2014,5,19,2014-05-19,0
138,1,2,7,27,10,1,0,4,87.166667,70.750000,59.541667,13.166667,263.583333,29.705000,1.250000,2014,5,20,2014-05-20,0
139,2,4,9,15,6,1,0,3,88.391304,72.478261,60.869565,13.391304,267.217391,27.074348,1.565217,2014,5,21,2014-05-21,0
140,3,1,1,8,8,0,2,4,87.791667,71.250000,59.250000,14.333333,261.750000,29.592500,1.083333,2014,5,22,2014-05-22,0
141,5,2,4,17,8,2,10,7,88.041667,73.541667,63.166667,13.916667,257.166667,29.532500,1.083333,2014,5,23,2014-05-23,0
142,3,4,5,28,11,1,0,9,88.545455,75.590909,66.772727,10.181818,247.772727,28.219091,1.000000,2014,5,24,2014-05-24,0
143,2,3,1,7,8,0,5,1,88.500000,75.750000,67.083333,8.416667,250.416667,29.593750,1.125000,2014,5,25,2014-05-25,0
144,2,3,7,18,7,1,0,5,88.416667,74.666667,65.875000,7.291667,245.833333,29.617500,2.000000,2014,5,26,2014-05-26,0
145,0,2,5,29,12,1,1,6,89.041667,73.000000,62.375000,10.708333,275.916667,29.623750,1.333333,2014,5,27,2014-05-27,0
146,1,5,1,10,9,0,2,5,88.173913,74.608696,65.521739,13.913043,269.217391,29.614348,1.043478,2014,5,28,2014-05-28,0
147,4,5,6,26,13,0,0,2,87.565217,74.478261,65.869565,24.086957,254.608696,29.603913,3.782609,2014,5,29,2014-05-29,0
148,2,1,2,20,12,0,0,5,88.565217,74.043478,63.130435,18.043478,249.826087,29.567391,4.043478,2014,5,30,2014-05-30,0
149,6,3,2,28,10,0,15,2,83.916667,72.541667,65.333333,15.916667,247.916667,28.307917,4.541667,2014,5,31,2014-05-31,0
150,1,0,1,10,4,1,1,3,89.304348,75.695652,64.956522,12.869565,253.695652,29.555652,2.695652,2014,6,1,2014-06-01,0
151,4,4,10,23,16,3,0,3,91.043478,75.130435,60.956522,13.565217,232.086957,29.605217,2.086957,2014,6,2,2014-06-02,0
152,3,2,2,24,7,2,5,3,91.166667,74.750000,59.708333,11.958333,245.875000,29.548750,4.375000,2014,6,3,2014-06-03,0
153,1,4,3,24,6,0,1,2,89.958333,75.833333,64.750000,12.750000,260.833333,29.491250,1.541667,2014,6,4,2014-06-04,0
154,0,4,4,22,4,0,0,5,92.333333,73.916667,56.916667,13.833333,259.958333,25.786250,1.125000,2014,6,5,2014-06-05,0
155,5,1,3,17,15,2,1,5,89.458333,74.791667,64.666667,14.416667,252.416667,29.467500,1.416667,2014,6,6,2014-06-06,0
156,9,3,7,33,8,1,6,7,88.913043,75.782609,66.086957,17.000000,257.391304,29.439565,2.347826,2014,6,7,2014-06-07,0
157,1,2,3,11,8,0,6,2,92.083333,74.541667,59.833333,12.125000,228.958333,14.675000,3.083333,2014,6,8,2014-06-08,0
158,6,1,5,18,17,4,0,11,89.041667,79.000000,72.333333,12.666667,194.166667,7.347917,3.625000,2014,6,9,2014-06-09,0
159,8,2,4,23,16,2,2,7,88.375000,74.750000,64.666667,14.250000,216.875000,28.214167,4.041667,2014,6,10,2014-06-10,0
160,4,0,2,13,16,2,12,9,88.875000,72.583333,59.541667,11.208333,220.583333,29.448750,1.625000,2014,6,11,2014-06-11,0
161,4,3,1,16,12,0,2,3,89.583333,74.083333,61.208333,10.916667,207.458333,29.437500,4.000000,2014,6,12,2014-06-12,0
162,1,2,5,10,11,0,3,1,88.250000,75.083333,65.541667,12.666667,175.416667,28.220417,4.666667,2014,6,13,2014-06-13,0
163,4,4,6,8,9,0,1,2,89.521739,76.826087,66.782609,10.739130,194.913043,25.594348,4.347826,2014,6,14,2014-06-14,0
164,0,2,0,8,5,0,0,3,91.250000,77.000000,64.250000,12.500000,230.833333,29.417500,3.833333,2014,6,15,2014-06-15,0
165,4,4,7,12,11,0,5,5,90.521739,75.521739,62.260870,14.304348,236.086957,26.861739,4.000000,2014,6,16,2014-06-16,0
166,5,2,4,14,12,2,0,3,89.041667,75.333333,64.333333,16.333333,236.583333,29.406250,5.375000,2014,6,17,2014-06-17,0
167,2,2,5,18,6,0,1,3,89.208333,77.333333,68.125000,14.750000,223.416667,29.349167,5.625000,2014,6,18,2014-06-18,0
168,3,3,1,14,8,0,0,1,90.333333,78.583333,68.625000,12.000000,223.375000,29.319583,4.625000,2014,6,19,2014-06-19,0
169,7,2,3,14,9,0,3,6,91.260870,77.434783,64.652174,13.913043,236.086957,28.053478,3.739130,2014,6,20,2014-06-20,0
170,6,5,2,16,12,3,0,3,91.375000,78.250000,65.791667,18.041667,241.250000,29.353750,5.166667,2014,6,21,2014-06-21,0
171,3,1,4,17,5,0,2,3,90.043478,78.130435,68.217391,20.652174,257.521739,29.423913,5.869565,2014,6,22,2014-06-22,0
172,2,7,3,25,12,0,2,3,89.521739,75.956522,65.043478,22.173913,250.826087,28.180000,8.173913,2014,6,23,2014-06-23,0
173,3,5,4,16,23,0,2,4,89.416667,75.500000,64.166667,23.791667,248.916667,29.417500,10.000000,2014,6,24,2014-06-24,0
174,8,5,7,34,19,0,0,1,89.083333,73.541667,60.750000,21.083333,250.666667,29.426250,8.375000,2014,6,25,2014-06-25,0